### PR TITLE
name, test PR

### PR DESCRIPTION
**Pull request by simonguozirui**

### CODE REVIEW

**Comment by simonguozirui** [comment]
[commit 7b9d140552a5db5081a9002cb302e44f2264adb1](https://github.com/projectclarify/clarify/commit/7b9d140552a5db5081a9002cb302e44f2264adb1) This edit to  `.gitignore` ignores node module for commits when client app is locally built.
@cwbeitel  Please decide whether `package-lock.json` in `client` should be ignored as well, depends on how the CI testing environment is set up.

**Comment by cwbeitel** [comment]
Related to https://github.com/projectclarify/clarify/issues/163

**Pull request merged**
